import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { MSWComponent } from './_providers/msw-component'
import './globals.css'
import { MainHeader } from '@/widgets/header'
import { Toaster } from '@/shared/ui/sonner'
import ReactQueryProviders from './_providers/react-query-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MSWComponent />
        <MainHeader />

        <Toaster />
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  )
}
